name: Pull Request

on: 
  pull_request:
    branches:
      - develop
      - staging
      - production
    types:
      - opened
      - synchronize

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on:
      group: Self-Hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: The current user
        run: | 
          echo "The current user is: $(whoami)"
      - name: Move and rename for docker compose file
        run: | 
          rm -rf docker-compose.yml
          mv ./docker/merge/docker-compose.yml ./docker-compose.yml
          ls ${{ github.workspace }}
          docker compose down -v
      - name: Build the docker compose
        run: docker compose up -d --build
      - name: Clear the resources
        run: docker compose down -v
      